name: test-runner

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
     inputs:
      test_input_1:
        type: string
        default: "test_input_1_value"
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  test_job:
    name: test job
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [16, 18, 20] # Define the matrix variable(s)
        os: [ubuntu-latest, windows-latest]
    steps:
    - name: Dump GitHub context
      run: |
        #echo "GITHUB_CONTEXT: ${{ toJSON(github) }}"
        echo "${{ matrix.os }}"
        echo "${{ matrix.version }}"
